updated CD fie.. again

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,11 +36,15 @@ jobs:
 
       - name: Create kubeconfig
         run: |
-          mkdir -p $HOME/.kube
-          sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
-          sudo chown $(id -u):$(id -g) $HOME/.kube/config
+          sudo mkdir -p $HOME/.kube
+          if [ -f /etc/rancher/k3s/k3s.yaml ]; then
+            sudo cp /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
+            sudo chown $(id -u):$(id -g) $HOME/.kube/config
+          else
+            echo "k3s.yaml not found"
+            exit 1
+          fi
           cat ${HOME}/.kube/config
-
       - name: Replace Public IP in Ingress Manifest
         run: |
           sed -i "s/\${PUBLIC_IP}/$PUBLIC_IP/g" k8s/ingress.yml
